spring:
  application:
    name: userservice

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: userinfo-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.aman.userservice.deserializer.UserEventUnifiedDeserializer
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: auth:com.aman.userservice.entities.UserInfoDTO

    topic-json:
      name: user_service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/userservice?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: password

    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 9810

logging:
  level:
    org.springframework.security: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG